//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESBX_Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESBX_Client.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa je obavezna..
        /// </summary>
        internal static string adresa_req {
            get {
                return ResourceManager.GetString("adresa_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos cijene je obavezan..
        /// </summary>
        internal static string cijena_req {
            get {
                return ResourceManager.GetString("cijena_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo Vas da definišete datum..
        /// </summary>
        internal static string datum_time {
            get {
                return ResourceManager.GetString("datum_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir dobavljaca je obavezan..
        /// </summary>
        internal static string dobvaljaci_req {
            get {
                return ResourceManager.GetString("dobvaljaci_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je u pogresnom formatu..
        /// </summary>
        internal static string email_format {
            get {
                return ResourceManager.GetString("email_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email je obavezan..
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnik sa unesenim emailom vec postoji..
        /// </summary>
        internal static string email_unique {
            get {
                return ResourceManager.GetString("email_unique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad je obavezan..
        /// </summary>
        internal static string grad_req {
            get {
                return ResourceManager.GetString("grad_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos gramaze je obavezan..
        /// </summary>
        internal static string gramaza_req {
            get {
                return ResourceManager.GetString("gramaza_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime je obavezno..
        /// </summary>
        internal static string ime_req {
            get {
                return ResourceManager.GetString("ime_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos kalorija je obavezan..
        /// </summary>
        internal static string kalorije_req {
            get {
                return ResourceManager.GetString("kalorije_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unos količine je obavezan..
        /// </summary>
        internal static string kolicina_req {
            get {
                return ResourceManager.GetString("kolicina_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unjeli ste pogresne pristupne podatke..
        /// </summary>
        internal static string login_password_incorrect {
            get {
                return ResourceManager.GetString("login_password_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora sadrzavati barem tri karaktera..
        /// </summary>
        internal static string login_password_length {
            get {
                return ResourceManager.GetString("login_password_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezno polje..
        /// </summary>
        internal static string login_password_req {
            get {
                return ResourceManager.GetString("login_password_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko ime mora zadrzavati barem tri karaktera..
        /// </summary>
        internal static string login_username_length {
            get {
                return ResourceManager.GetString("login_username_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko ime je obavezno polje..
        /// </summary>
        internal static string login_username_req {
            get {
                return ResourceManager.GetString("login_username_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka mora sadržavati više od 6 karaktera..
        /// </summary>
        internal static string lozinka_length {
            get {
                return ResourceManager.GetString("lozinka_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lozinka je obavezna..
        /// </summary>
        internal static string lozinka_req {
            get {
                return ResourceManager.GetString("lozinka_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv sastojka je obavezno polje..
        /// </summary>
        internal static string naziv_sastojak_req {
            get {
                return ResourceManager.GetString("naziv_sastojak_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molimo Vas da definišete popust za korisnika..
        /// </summary>
        internal static string popust_req {
            get {
                return ResourceManager.GetString("popust_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prezime je obavezno..
        /// </summary>
        internal static string prezime_req {
            get {
                return ResourceManager.GetString("prezime_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odabir sastojaka je obavezan..
        /// </summary>
        internal static string sastojak_req {
            get {
                return ResourceManager.GetString("sastojak_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon je obavezan..
        /// </summary>
        internal static string telefon_req {
            get {
                return ResourceManager.GetString("telefon_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrsta sastojka je obavezno polje..
        /// </summary>
        internal static string vrstaSastojka_req {
            get {
                return ResourceManager.GetString("vrstaSastojka_req", resourceCulture);
            }
        }
    }
}
