//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpressSaladBarDesktop_API.Helper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpressSaladBarDesktop_API.Helper.messages", typeof(messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to asdadadas.
        /// </summary>
        internal static string aaa {
            get {
                return ResourceManager.GetString("aaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/sastojci/deletebyid/.
        /// </summary>
        internal static string DELETE_VRSTE_SASTOJAKA {
            get {
                return ResourceManager.GetString("DELETE_VRSTE_SASTOJAKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/korpa/narudzbe/.
        /// </summary>
        internal static string GET_OSOBLJE_KORPA {
            get {
                return ResourceManager.GetString("GET_OSOBLJE_KORPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/sastojci/.
        /// </summary>
        internal static string GET_SASTOJCI {
            get {
                return ResourceManager.GetString("GET_SASTOJCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/sastojci/vrstesastojaka/.
        /// </summary>
        internal static string GET_VRSTE_SASTOJAKA {
            get {
                return ResourceManager.GetString("GET_VRSTE_SASTOJAKA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/sastojci/addSastojak.
        /// </summary>
        internal static string POST_SASTOJCI {
            get {
                return ResourceManager.GetString("POST_SASTOJCI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:58050/.
        /// </summary>
        internal static string URL_ROUTE {
            get {
                return ResourceManager.GetString("URL_ROUTE", resourceCulture);
            }
        }
    }
}
